### ISSUE TITLE
document how to address devices via serial console

### ISSUE THREAD

**Issue by PeterNerlich** [greenpau/ndmtk#20]
In the documentation, when searching for "console" or "expect", the only hits are in the README, which speaks of this being part of the feature set. But how to address these devices (especially since Ansible itself usually only uses domains or IP addresses) is not explained.

**Comment by greenpau** [comment]
@PeterNerlich , for this you would need `socat`.

The following command link serial port `ttyXX` to a localhost TCP port, e.g. `3231`. It would similar to this. You would need to tinker a bit :smile: 

```
socat /dev/ttyXX,raw,echo=0,crnl TCP4:localhost:3231
```

Then, you will use the following config in `hosts`

```
ny-fw02-via-console os=cisco_asa host_overwrite=127.0.0.1 host_protocol=telnet host_port=3231
```

Hope this explains it.

**Comment by PeterNerlich** [comment]
Okay, thank you.

I'm trying to look into ways of addressing a few currently unsupported switches/firewalls by MOXA and HIRSCHMANN. I don't know if CISCO does the same or not, but they offer an interactive serial console which is clearly not made for easy automated interfacing. Can I expect this to be as easy as to add them as a system type and specify the command set and return format or does this currently rely on features unlikely to exist with a conventional interactive serial console?

**Comment by greenpau** [comment]
> interactive serial console which is clearly not made for easy automated interfacing

@PeterNerlich , I think in that case please use `generic_linux` device type. 

> Can I expect this to be as easy as to add them as a system type and specify the command set and return format or does this currently rely on features unlikely to exist with a conventional interactive serial console?

You would need to tinker with it and look at debug logs.  Set "debug=yes" in a playbook, e.g.

```
---
- name: generic data collection
  hosts:
  - ny-fw01-via-console
  gather_facts: no
  tasks:
  - name: data collection from three network devices
    action: ndmtk output="/tmp/ndmtk-%Y%m%d%H%M%S" debug=yes no_host_key_check=yes on_error=continue
```
